#ifndef __VERSION_PARTITION_H__
#define __VERSION_PARTITION_H__

#define VERSION_NUMBER "QEMU-Virt-PanZX-V1.0.0"
#define STORDEV_NAME "/dev/sda"
#define STORDEV_PHYSICAL_BLKSIZE 0x200
#define STORDEV_PARTTABLE_SIZE (STORDEV_PHYSICAL_BLKSIZE * 34)
#define KERNEL_PARTITION_SIZE 0x00600000    // headers + kernel image
#define ROOTFS_PARTITION_SIZE 0x03000000
#define VERSION_PARTITION_SIZE (KERNEL_PARTITION_SIZE + ROOTFS_PARTITION_SIZE)

/** GPT part table
 * block0 protect MBR
 * block1 GPT header
 * block2-block33 main partition table
 * ...
 * last 34 block save backup partitiontable and backup GPT header
*/

// header is at the beginning of the partition
#define SIGN_HEADER_OFFSET 0x0
#define VERSION_HEADER_OFFSET STORDEV_PHYSICAL_BLKSIZE
#define KERNEL_OFFSET (2 * STORDEV_PHYSICAL_BLKSIZE)

#define VERSION0_PARTITION_OFFSET STORDEV_PARTTABLE_SIZE
#define VERSION0_PARTITION_SIZE   VERSION_PARTITION_SIZE
#define VERSION0_ROOTFS_PARTITION "/dev/sda2"

#define VERSION1_PARTITION_OFFSET (VERSION0_PARTITION_OFFSET + VERSION0_PARTITION_SIZE)
#define VERSION1_PARTITION_SIZE   VERSION_PARTITION_SIZE
#define VERSION1_ROOTFS_PARTITION "/dev/sda4"

#endif
