#ifndef __VERSION_PARTITION_H__
#define __VERSION_PARTITION_H__

#define VERSION_NUMBER "QEMU-Virt-PanZX-V1.0.0"
#define STORDEV_NAME "/dev/sda"
#define STORDEV_PHYSICAL_BLKSIZE 0x200
#define STORDEV_PARTTABLE_SIZE 0x00100000
#define KERNEL_PARTITION_SIZE 0x00800000
#define ROOTFS_PARTITION_SIZE 0x01800000
#define VER_HEADER_BLOCK_SIZE  STORDEV_PHYSICAL_BLKSIZE

/** GPT part table
 * block0 protect MBR
 * block1 GPT header
 * block2-block33 main partition table
 * ...
 * last 34 block save backup partitiontable and backup GPT header
*/

// version header is at the first block in kernel partition
#define KERNEL1_PARTITION_NAME   "/dev/sda1"
#define KERNEL1_PARTITION_OFFSET STORDEV_PARTTABLE_SIZE
#define KERNEL1_PARTITION_SIZE   KERNEL_PARTITION_SIZE

#define ROOTFS1_PARTITION_NAME   "/dev/sda2"
#define ROOTFS1_PARTITION_OFFSET (KERNEL1_PARTITION_OFFSET + KERNEL1_PARTITION_SIZE)
#define ROOTFS1_PARTITION_SIZE   ROOTFS_PARTITION_SIZE

#define KERNEL2_PARTITION_NAME   "/dev/sda3"
#define KERNEL2_PARTITION_OFFSET (ROOTFS1_PARTITION_OFFSET + ROOTFS1_PARTITION_SIZE)
#define KERNEL2_PARTITION_SIZE   KERNEL_PARTITION_SIZE

#define ROOTFS2_PARTITION_NAME   "/dev/sda2"
#define ROOTFS2_PARTITION_OFFSET (KERNEL2_PARTITION_OFFSET + KERNEL2_PARTITION_SIZE)
#define ROOTFS2_PARTITION_SIZE   ROOTFS_PARTITION_SIZE

#endif