#!/bin/sh

mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ramdom c 1 8
mknod -m 666 /dev/uramdom c 1 9

mknod -m 666 /dev/tty0 c 4 0
mknod -m 666 /dev/tty1 c 4 1
mknod -m 666 /dev/tty2 c 4 2
mknod -m 666 /dev/tty3 c 4 3
mknod -m 666 /dev/tty4 c 4 4

mknod -m 666 /dev/tty c 5 0
mknod -m 666 /dev/console c 5 1

mknod -m 666 /dev/ttyAMA0 c 204 64

mknod -m 660 /dev/sda b 8 0